import { describe, expect, test } from 'bun:test';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { runInit } from './init.ts';

function scratch(): string {
  return mkdtempSync(join(tmpdir(), 'rubric-init-'));
}

describe('runInit', () => {
  test('writes config, prompts, and dataset into an empty directory', async () => {
    const dir = scratch();
    try {
      const result = await runInit({ cwd: dir });

      expect(result.skipped).toEqual([]);
      expect(result.written.map((p) => p.replace(dir + '/', ''))).toEqual([
        'rubric.config.json',
        'prompts/baseline.md',
        'prompts/candidate.md',
        'data/cases.jsonl',
      ]);

      const config = JSON.parse(readFileSync(join(dir, 'rubric.config.json'), 'utf8'));
      expect(config.prompts.baseline).toBe('prompts/baseline.md');
      expect(config.dataset).toBe('data/cases.jsonl');
      expect(config.mode).toBe('compare-prompts');

      const lines = readFileSync(join(dir, 'data/cases.jsonl'), 'utf8').trim().split('\n');
      expect(lines.length).toBe(5);
      for (const line of lines) {
        const parsed = JSON.parse(line);
        expect(typeof parsed.input).toBe('string');
        expect(typeof parsed.metadata?.category).toBe('string');
      }
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('skips existing files by default and overwrites with --force', async () => {
    const dir = scratch();
    try {
      await runInit({ cwd: dir });
      const first = await runInit({ cwd: dir });
      expect(first.written).toEqual([]);
      expect(first.skipped.length).toBe(4);

      const second = await runInit({ cwd: dir, force: true });
      expect(second.written.length).toBe(4);
      expect(second.skipped).toEqual([]);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('--wizard --mock --describe generates templated prompts + 10 tagged cases', async () => {
    const dir = scratch();
    try {
      const result = await runInit({
        cwd: dir,
        wizard: true,
        describe: 'summarize legal contracts for a non-lawyer audience',
        mock: true,
      });
      expect(result.autogeneratedCases).toBe(10);

      const baseline = readFileSync(join(dir, 'prompts/baseline.md'), 'utf8');
      const candidate = readFileSync(join(dir, 'prompts/candidate.md'), 'utf8');
      expect(baseline).toContain('{{input}}');
      expect(candidate).toContain('{{input}}');
      expect(baseline).toContain('Summarize legal contracts for a non-lawyer audience');

      const lines = readFileSync(join(dir, 'data/cases.jsonl'), 'utf8').trim().split('\n');
      expect(lines.length).toBe(10);
      for (const line of lines) {
        const parsed = JSON.parse(line);
        expect(typeof parsed.input).toBe('string');
        expect(parsed.metadata._autogenerated).toBe(true);
      }
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });

  test('--wizard without --describe errors before writing files', async () => {
    const dir = scratch();
    try {
      await expect(runInit({ cwd: dir, wizard: true, mock: true })).rejects.toThrow(/--describe/);
    } finally {
      rmSync(dir, { recursive: true, force: true });
    }
  });
});
