import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import {
  createOpenAIProvider,
  splitModelId,
  type ModelId,
  type Provider,
} from '../../../shared/src/index.ts';

const CONFIG_FILE = 'rubric.config.json';
const PROMPTS_DIR = 'prompts';
const DATA_DIR = 'data';

const DEFAULT_CONFIG = {
  $schema: 'https://rubric.dev/schema/v1.json',
  prompts: {
    baseline: 'prompts/baseline.md',
    candidate: 'prompts/candidate.md',
  },
  dataset: 'data/cases.jsonl',
  models: ['openai/gpt-4o-mini'],
  judge: {
    model: 'openai/gpt-4o',
    criteria: 'default',
  },
  concurrency: 4,
  mode: 'compare-prompts',
};

const BASELINE_PROMPT = `You are a customer support agent. Read the ticket and reply concisely.

Ticket: {{input}}
`;

const CANDIDATE_PROMPT = `You are a customer support agent. Read the ticket and reply. In your reply:

- Acknowledge the specific issue (name it, don't just say "sorry to hear that").
- State the concrete next step you're taking or need from the customer.
- Set a clear expectation about timing.

Ticket: {{input}}
`;

// Five representative tickets covering billing, account recovery, bugs, and
// cancellation. Picked for contrast between a vague/dismissive baseline and a
// specific/action-oriented candidate. See examples/support-tickets.jsonl for
// the full 50-row launch dataset.
const EXAMPLE_CASES = [
  {
    input: 'I was charged twice this month. Can you refund the duplicate?',
    metadata: { category: 'billing' },
  },
  {
    input: "Can't log in. Password reset email never arrives. Tried 4 times.",
    metadata: { category: 'account' },
  },
  {
    input: 'Your app crashed three times in a row when I tried to upload a PDF.',
    metadata: { category: 'bug' },
  },
  {
    input: 'I cancelled my subscription yesterday but was charged again today at midnight.',
    metadata: { category: 'refund' },
  },
  {
    input: 'Please help me ASAP this is urgent!!!',
    metadata: { category: 'unclear' },
  },
];

export interface InitOptions {
  cwd?: string;
  force?: boolean;
  /** Judge-assisted scaffold mode. Requires `describe`. */
  wizard?: boolean;
  /** One-sentence description of the task to bootstrap prompts + cases around. */
  describe?: string;
  /** For --wizard: use deterministic templated generation instead of an LLM call. */
  mock?: boolean;
}

export interface InitResult {
  written: string[];
  skipped: string[];
  /** Number of cases emitted by the wizard (0 for non-wizard runs). */
  autogeneratedCases: number;
}

interface Scaffold {
  baseline: string;
  candidate: string;
  cases: Array<{ input: string; metadata?: Record<string, unknown> }>;
}

export async function runInit(opts: InitOptions = {}): Promise<InitResult> {
  const cwd = resolve(opts.cwd ?? process.cwd());
  const force = opts.force ?? false;
  const wizard = opts.wizard ?? false;

  let baseline = BASELINE_PROMPT;
  let candidate = CANDIDATE_PROMPT;
  let cases: Array<{ input: string; metadata?: Record<string, unknown> }> = EXAMPLE_CASES;
  let autogeneratedCases = 0;

  if (wizard) {
    const describe = opts.describe?.trim();
    if (!describe) {
      throw new Error('--wizard requires --describe "<one-sentence task description>"');
    }
    const scaffold = await generateScaffold(describe, opts.mock === true);
    baseline = scaffold.baseline;
    candidate = scaffold.candidate;
    // Tag every auto-generated case so reviewers know not to trust them blindly.
    cases = scaffold.cases.map((c) => ({
      input: c.input,
      metadata: { ...(c.metadata ?? {}), _autogenerated: true },
    }));
    autogeneratedCases = cases.length;
  }

  const files: Array<{ path: string; content: string }> = [
    { path: join(cwd, CONFIG_FILE), content: JSON.stringify(DEFAULT_CONFIG, null, 2) + '\n' },
    { path: join(cwd, PROMPTS_DIR, 'baseline.md'), content: baseline },
    { path: join(cwd, PROMPTS_DIR, 'candidate.md'), content: candidate },
    {
      path: join(cwd, DATA_DIR, 'cases.jsonl'),
      content: cases.map((c) => JSON.stringify(c)).join('\n') + '\n',
    },
  ];

  mkdirSync(join(cwd, PROMPTS_DIR), { recursive: true });
  mkdirSync(join(cwd, DATA_DIR), { recursive: true });

  const written: string[] = [];
  const skipped: string[] = [];

  for (const file of files) {
    if (existsSync(file.path) && !force) {
      skipped.push(file.path);
      continue;
    }
    writeFileSync(file.path, file.content, 'utf8');
    written.push(file.path);
  }

  return { written, skipped, autogeneratedCases };
}

async function generateScaffold(describe: string, mock: boolean): Promise<Scaffold> {
  if (mock) return mockScaffold(describe);

  const apiKey = process.env.OPENAI_API_KEY;
  if (!apiKey) {
    throw new Error(
      '--wizard requires OPENAI_API_KEY (or pass --mock for deterministic templates without an LLM call)',
    );
  }
  const provider = createOpenAIProvider({ apiKey });
  const model = 'openai/gpt-4o-mini' as ModelId;
  return llmScaffold(provider, model, describe);
}

function mockScaffold(describe: string): Scaffold {
  const baseline = `You are an assistant. ${capitalize(describe)}.

Input: {{input}}
`;
  const candidate = `You are an assistant. ${capitalize(describe)}.

Your reply must:
- Restate the core ask in one line so the user knows you understood it.
- Give the concrete answer or next step (no hedging, no filler).
- If information is missing, ask ONE targeted question rather than a list.

Input: {{input}}
`;
  // 10 placeholder prompts that vary in shape (clear request, ambiguous,
  // multi-part, short, long, edge) so the judge has signal to work with even
  // before the user hand-curates.
  const cases = [
    `Straightforward request about ${describe}.`,
    `Ambiguous question related to ${describe}, missing key context.`,
    `Multi-part question about ${describe} with two unrelated asks.`,
    `Edge case: user asking about ${describe} with conflicting constraints.`,
    `Very short request: "${describe.split(' ').slice(0, 3).join(' ')}?"`,
    `Long-form narrative context before a question about ${describe}.`,
    `Request about ${describe} with a follow-up "why?" embedded.`,
    `Polite but urgent request about ${describe} from a frustrated user.`,
    `Technical-jargon-heavy question about ${describe}.`,
    `Plain-language beginner question about ${describe}.`,
  ].map((input, i) => ({ input, metadata: { seed_index: i } }));

  return { baseline, candidate, cases };
}

async function llmScaffold(provider: Provider, model: ModelId, describe: string): Promise<Scaffold> {
  const { model: resolvedModel } = splitModelId(model);
  void resolvedModel;

  const system = [
    'You are helping a developer bootstrap a prompt-evaluation workspace.',
    'Given a one-sentence task description, produce:',
    '  1. a BASELINE prompt — a terse, minimal version a lazy engineer would ship first.',
    '  2. a CANDIDATE prompt — an improved version that is specific, structured, and actionable.',
    '  3. 10 diverse INPUT CASES that exercise the task, with variety across clarity, length, ambiguity, and edge cases.',
    'Both prompts MUST include the literal placeholder `{{input}}` where the user input goes.',
    'Respond with ONLY a single JSON object, no code fences, no prose:',
    '{"baseline":"...","candidate":"...","cases":[{"input":"..."}, ...]}',
  ].join('\n');

  const prompt = `Task description: ${describe}`;

  const result = await provider.generate({
    modelId: model,
    system,
    prompt,
    temperature: 0.4,
  });

  const parsed = extractScaffold(result.text);
  // Harden against models that forget the placeholder — wizard output without
  // {{input}} would produce identical completions on every case.
  if (!parsed.baseline.includes('{{input}}')) {
    parsed.baseline = `${parsed.baseline.trimEnd()}\n\nInput: {{input}}\n`;
  }
  if (!parsed.candidate.includes('{{input}}')) {
    parsed.candidate = `${parsed.candidate.trimEnd()}\n\nInput: {{input}}\n`;
  }
  return parsed;
}

function extractScaffold(raw: string): Scaffold {
  const trimmed = raw.trim();
  let parsed: unknown;
  try {
    parsed = JSON.parse(trimmed);
  } catch {
    const first = trimmed.indexOf('{');
    const last = trimmed.lastIndexOf('}');
    if (first === -1 || last === -1 || last <= first) {
      throw new Error(`wizard: LLM did not return JSON (raw: ${preview(raw)})`);
    }
    try {
      parsed = JSON.parse(trimmed.slice(first, last + 1));
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      throw new Error(`wizard: LLM returned malformed JSON (${msg})`);
    }
  }

  if (typeof parsed !== 'object' || parsed === null || Array.isArray(parsed)) {
    throw new Error('wizard: LLM response was not a JSON object');
  }
  const rec = parsed as Record<string, unknown>;
  if (typeof rec.baseline !== 'string' || rec.baseline.length === 0) {
    throw new Error('wizard: missing "baseline" string in LLM response');
  }
  if (typeof rec.candidate !== 'string' || rec.candidate.length === 0) {
    throw new Error('wizard: missing "candidate" string in LLM response');
  }
  if (!Array.isArray(rec.cases) || rec.cases.length === 0) {
    throw new Error('wizard: missing "cases" array in LLM response');
  }
  const cases: Array<{ input: string; metadata?: Record<string, unknown> }> = [];
  for (let i = 0; i < rec.cases.length; i++) {
    const c = rec.cases[i];
    if (typeof c !== 'object' || c === null || Array.isArray(c)) continue;
    const input = (c as Record<string, unknown>).input;
    if (typeof input !== 'string' || input.length === 0) continue;
    cases.push({ input });
  }
  if (cases.length === 0) {
    throw new Error('wizard: LLM returned no usable cases');
  }
  return { baseline: rec.baseline, candidate: rec.candidate, cases };
}

function preview(s: string): string {
  const trimmed = s.trim().replace(/\s+/g, ' ');
  return trimmed.length > 120 ? trimmed.slice(0, 117) + '...' : trimmed;
}

function capitalize(s: string): string {
  if (s.length === 0) return s;
  return s[0]!.toUpperCase() + s.slice(1);
}
